hmlsvcr/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView
from hmlsvcrapp.views import AdminPasswordResetView  # Import the view here

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hmlsvcrapp/', include('hmlsvcrapp.urls')),
    path('', RedirectView.as_view(url='/hmlsvcrapp/', permanent=True)),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
]

hmlsvcrapp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import LoginView
from django.contrib import admin
from .views import CustomLoginView, ToggleStaffStatusView, get_network_details, get_server_details
from hmlsvcrapp.views import AdminPasswordResetView

urlpatterns = [
    path('servers/', views.server_list, name='server_list'),
    path('services/', views.service_list, name='service_list'),
    path('networks/', views.network_list, name='network_list'),
    path('credentials/', views.credential_list, name='credential_list'),
    path('monitors/', views.list_monitors, name='list_monitors'),
    path('', views.index, name='index'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('', RedirectView.as_view(url='/hmlsvcrapp/', permanent=True)),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('networks/<int:network_id>/edit/', views.edit_network, name='edit_network'),
    path('add_network/', views.add_network, name='add_network'),
    path('networks/<int:network_id>/delete/', views.delete_network, name='delete_network'),
    path('add_service/', views.add_service, name='add_service'),
    path('services/<int:service_id>/delete/', views.delete_service, name='delete_service'),
    path('services/<int:service_id>/edit/', views.edit_service, name='edit_service'),
    path('add_server/', views.add_server, name='add_server'),
    path('servers/<int:server_id>/delete/', views.delete_server, name='delete_server'),
    path('servers/<int:server_id>/edit/', views.edit_server, name='edit_server'),
    path('services/<int:service_id>/decommission/', views.decommission_service, name='decommission_service'),
    path('add_credential/', views.add_credential, name='add_credential'),
    path('credentials/<int:credential_id>/edit/', views.edit_credential, name='edit_credential'),
    path('credentials/<int:credential_id>/delete/', views.delete_credential, name='delete_credential'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('admin/', admin.site.urls),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    #path('edit_user_profile/', views.edit_user_profile, name='edit_user_profile'),
    path('edit_user_profile/<int:user_id>', views.edit_user_profile, name='edit_user_profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='hmlsvcrapp/edit_password.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='hmlsvcrapp/password_change_done.html'), name='password_change_done'),
    path('users/', views.user_list, name='user_list'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('add_user/', views.add_user, name='add_user'),
    path('edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
    path('edit/profile/<int:user_id>/deactivate/', views.deactivate_user, name='deactivate_user'),
    path('edit/superuser/<int:user_id>/', views.edit_superuser_profile, name='edit_superuser_profile'),
    path('edit/staff/<int:user_id>/', views.edit_staff_profile, name='edit_staff_profile'),
    path('edit/profile/', views.edit_user_profile, name='edit_user_profile'),
    path('edit/users/<int:user_id>/reset-password/', AdminPasswordResetView.as_view(), name='admin_password_reset'),
    path('edit/users/<int:user_id>/toggle-staff/', ToggleStaffStatusView.as_view(), name='toggle_staff_status'),
    path('get-network-details/<int:network_id>/', get_network_details, name='get_network_details'),
    path('get-server-details/<int:server_id>/', get_server_details, name='get_server_details'),
    #path('networks/<int:network_id>/edit/', views.edit_network, name='hmlsvcrapp_network_change'),
    # other URL patterns...
    # Add other URL patterns here
]

hmlsvcrapp/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from django.db import models

import ipaddress

def generate_subnet_mask_choices():
    choices = []
    for cidr in range(32, -1, -1):  # Starts at 32, ends at 0, steps backwards
        mask = str(ipaddress.IPv4Network(f'0.0.0.0/{cidr}').netmask)
        num_hosts = 2 ** (32 - cidr) - 2  # Usable hosts
        # Handling special cases for /31 and /32 subnets
        if cidr in [31, 32]:
            host_info = 'Self' if cidr == 32 else '1 usable host (point-to-point)'
        else:
            host_info = f'{num_hosts} hosts'
        choices.append((f'/{cidr} - {mask} - {host_info}', f'/{cidr} - {mask} - {host_info}'))
    return choices

class Network(models.Model):
    name = models.CharField(max_length=255)
    vlan_id = models.IntegerField()
    ip_space = models.CharField(max_length=18)
    subnet_mask = models.CharField(max_length=255, choices=generate_subnet_mask_choices())

    def __str__(self):
        return self.name

class Server(models.Model):
    SERVER_TYPES = [
        ('VM', 'Virtual Machine'),
        ('Docker', 'Docker'),
        ('Physical', 'Physical'),
        ('LXC', 'Linux Container'),
        ('Other', 'Other'),
    ]

    OS_CHOICES = [
        ('Debian', 'Debian'),
        ('Ubuntu', 'Ubuntu'),
        ('Windows', 'Windows'),
        ('OtherLinux', 'Other Linux'),
        ('macOS', 'macOS'),
        ('Other', 'Other'),
    ]

    name = models.CharField(max_length=255)
    ip_address = models.CharField(max_length=15)
    location = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    network = models.ForeignKey(Network, on_delete=models.SET_NULL, null=True, related_name='servers')
    type = models.CharField(max_length=50, choices=SERVER_TYPES)
    os = models.CharField(max_length=50, choices=OS_CHOICES)
    #credentials = models.ManyToManyField('Credential', related_name='servers', blank=True)
    cred_name = models.ForeignKey('Credential', on_delete=models.SET_NULL, null=True, blank=True, related_name='servers', to_field='cred_name')
    #uptimekumaurl = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

class Service(models.Model):
    STATUS_CHOICES = [
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
        ('Decommissioned', 'Decommissioned'),
    ]

    server = models.ForeignKey(Server, on_delete=models.SET_NULL, related_name='services', null=True)
    network = models.ForeignKey('Network', on_delete=models.SET_NULL, related_name='services', null=True, blank=True)
    name = models.CharField(max_length=255)
    port = models.IntegerField(validators=[MaxValueValidator(65535)])
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)
    ip = models.CharField(max_length=15)
    wazuh_agent_installed = models.BooleanField(default=False)
    fqdn = models.CharField(max_length=255, null=True, blank=True)
    cloudflare_proxy_configured = models.BooleanField(default=False)
    reverse_proxy_configured = models.BooleanField(default=False)
    ldn = models.CharField(max_length=255, null=True, blank=True)
    dns_configured = models.BooleanField(default=False)
    credentials = models.ManyToManyField('Credential', related_name='services', blank=True)
    https_enabled = models.BooleanField(default=False)
    cred_name = models.ForeignKey('Credential', on_delete=models.SET_NULL, null=True, blank=True, related_name='services_name', to_field='cred_name')
    #uptimekumaurl = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

class Credential(models.Model):
    MFA_SOURCES = [
        ('Phone', 'Phone'),
        ('iCloud', 'iCloud Passwords'),
        ('Bitwarden', 'Bitwarden Passwords'),
        ('None', 'Not configured/available'),
    ]

    ACCOUNT_TYPES = [
        ('Root', 'Root'),
        ('User', 'User'),
        ('Admin', 'Admin'),
        ('Other', 'Other'),
    ]

    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)  # Remember to handle encryption securely
    last_updated = models.DateField(null=True, blank=True)
    mfa_enabled = models.BooleanField()
    mfa_source = models.CharField(max_length=50, choices=MFA_SOURCES, blank=True, null=True)
    sso = models.BooleanField()
    account_type = models.CharField(max_length=50, choices=ACCOUNT_TYPES)
    cred_name = models.CharField(max_length=255, null=True, unique=True)
    #content_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True, blank=True)
    #object_id = models.PositiveIntegerField(null=True, blank=True)
    #related_item = GenericForeignKey('content_type', 'object_id')
    associated_server = models.ForeignKey(Server, on_delete=models.SET_NULL, null=True, blank=True, related_name='server_credentials')
    associated_service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True, related_name='service_credentials')

    def __str__(self):
        return self.cred_name



# Join Table for Server and Service
class ServerService(models.Model):
    server = models.ForeignKey(Server, on_delete=models.SET_NULL, null=True)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True)

    class Meta:
        unique_together = ('server', 'service')

class ServiceCredential(models.Model):
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True)
    credential = models.ForeignKey(Credential, on_delete=models.SET_NULL, null=True)

    class Meta:
        unique_together = ('service', 'credential')

    def __str__(self):
        return f"{self.service.name} - {self.credential.cred_name if self.credential else 'No Credential'}"

class ServerCredential(models.Model):
    server = models.ForeignKey(Server, on_delete=models.SET_NULL, null=True)
    credential = models.ForeignKey(Credential, on_delete=models.SET_NULL, null=True)

    class Meta:
        unique_together = ('server', 'credential')

    def __str__(self):
        return f"{self.server.name} - {self.credential.cred_name if self.credential else 'No Credential'}"

class UptimeKumaMonitors(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255)
    server = models.ForeignKey(Server, on_delete=models.SET_NULL, null=True, blank=True)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

hmlsvcrapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from .models import Network, Service, Server, Credential
from django.contrib.auth.views import LoginView

class NetworkForm(forms.ModelForm):
    class Meta:
        model = Network
        fields = '__all__'  # Include all fields from the Network model
        # If you want to include specific fields only, list them like ['name', 'ip_space', ...]

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'
        #fields = ['server', 'name', 'port', 'status', 'ip', 'wazuh_agent_installed', 'fqdn', 'cloudflare_proxy_configured', 'reverse_proxy_configured', 'ldn', 'dns_configured', 'credentials']

class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        fields = '__all__'  

class CredentialForm(forms.ModelForm):
    class Meta:
        model = Credential
        fields = '__all__'

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'
        #fields = ['first_name', 'last_name', 'email']  # Add other fields you need

class CustomUserChangeForm(UserChangeForm):
    is_active = forms.BooleanField(required=False)
    is_staff = forms.BooleanField(required=False)
    is_superuser = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('current_user', None)
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)

        # Conditionally remove the is_superuser field for non-superusers
        if not user.is_superuser:
            self.fields.pop('is_superuser')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'is_active', 'is_staff', 'is_superuser', 'groups', 'user_permissions']

    def save(self, commit=True):
        user = super().save(commit=False)

        # Only update fields if they are present in the form
        if 'is_active' in self.cleaned_data:
            user.is_active = self.cleaned_data['is_active']
        if 'is_staff' in self.cleaned_data:
            user.is_staff = self.cleaned_data['is_staff']
        if 'is_superuser' in self.cleaned_data:
            user.is_superuser = self.cleaned_data['is_superuser']

        if commit:
            user.save()
            self.save_m2m()  # Save many-to-many fields like groups and permissions

        return user

class CustomUserCreationForm(UserCreationForm):
    is_active = forms.BooleanField(initial=True, required=False)
    is_staff = forms.BooleanField(required=False)
    is_superuser = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('current_user', None)
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        if not user.is_superuser:
            self.fields.pop('is_superuser')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'is_active', 'is_staff', 'is_superuser']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = self.cleaned_data["is_active"]
        user.is_staff = self.cleaned_data["is_staff"]
        if 'is_superuser' in self.cleaned_data:
            user.is_superuser = self.cleaned_data["is_superuser"]
        if commit:
            user.save()
        return user

hmlsvcrapp/templates/hmlsvcrapp/add_credential.html
<!-- edit_credential.html -->
{% if request.user.is_authenticated %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Add Credential</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'hmlsvcrapp/formstyles.css' %}">
</head>
<body>
    <form method="post" class="container">
        {% csrf_token %}
        <h1>Add Credential</h1>
        <div class="form-container">
            <div class="column">
                <label for="id_cred_name">Credential Name:{% if form.cred_name.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.cred_name }}
                
                <label for="id_mfa_enabled">MFA Enabled:</label>
                {{ form.mfa_enabled }}

                <label for="id_mfa_source">MFA Source:</label>
                {{ form.mfa_source }}

                <label for="id_sso">SSO:</label>
                {{ form.sso }}

                <label for="id_last_updated">Last Updated:</label>
                {{ form.last_updated }}
            </div>
            <div class="column">
                <label for="id_username">Username:{% if form.username.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.username }}

                <label for="id_password">Password:{% if form.password.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.password }}

                <label for="id_account_type">Account Type:{% if form.account_type.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.account_type }}

                <label for="id_associated_server">Associated Server:</label>
                {{ form.associated_server }}

                <label for="id_associated_service">Associated Service:</label>
                {{ form.associated_service }}
            </div>
        </div>
        <div class="button-container">
            <button type="submit">Save Credential</button>
        </div>
</body>
</html>
{% else %}
{% include 'hmlsvcrapp/_menu.html' %}
<style>
.login-prompt-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
    text-align: center;
}

.login-message {
    font-size: 1.2em;
    margin-bottom: 20px;
    color: #333;
}

.login-button {
    display: inline-block;
    background-color: #009879;
    color: white;
    padding: 10px 20px;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s;
}

.login-button:hover {
    background-color: #007961;
}

</style>
    <div class="login-prompt-container">
        <p><h1>&#128273; <!-- Emoji for red x -->[RESTRICTED]</h1></p>
        <p><h3>You do not have permissions to view this page</h3></p>
    </div>
{% endif %}

hmlsvcrapp/templates/hmlsvcrapp/add_network.html
{% if request.user.is_authenticated %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Add New Network</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'hmlsvcrapp/formstyles.css' %}">
</head>
<body>
    <div class="container">
        <h1>Add New Network</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_name">Name:</label>
            {{ form.name }}
        
            <label for="id_vlan_id">VLAN ID:</label>
            {{ form.vlan_id }}
        
            <label for="id_ip_space">IP Space:</label>
            {{ form.ip_space }}
        
            <label for="id_subnet_mask">Subnet Mask:</label>
            {{ form.subnet_mask }}
        
            <button type="submit">Create Network</button>
        </form>        
    </div>
</body>
</html>
{% else %}
{% include 'hmlsvcrapp/_menu.html' %}
<style>
.login-prompt-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
    text-align: center;
}

.login-message {
    font-size: 1.2em;
    margin-bottom: 20px;
    color: #333;
}

.login-button {
    display: inline-block;
    background-color: #009879;
    color: white;
    padding: 10px 20px;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s;
}

.login-button:hover {
    background-color: #007961;
}

</style>
    <div class="login-prompt-container">
        <p><h1>&#128273; <!-- Emoji for red x -->[RESTRICTED]</h1></p>
        <p><h3>You do not have permissions to view this page</h3></p>
    </div>
{% endif %}

hmlsvcrapp/templates/hmlsvcrapp/add_service.html
{% if request.user.is_authenticated %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Service</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'hmlsvcrapp/formstyles.css' %}">
</head>
<body>
    <form method="post" class="container">
        <h1>Add New Service</h1>
        <div class="form-container">
            {% csrf_token %}
            <div class="column">
                <label for="id_status">Status:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.status }}
                
                <label for="id_https_enabled">HTTPS:</label>{{ form.https_enabled }}
                
                <label for="id_cloudflare_proxy_configured">Cloudflare:</label>{{ form.cloudflare_proxy_configured }}
                
                <label for="id_reverse_proxy_configured">Reverse Proxy:</label>{{ form.reverse_proxy_configured }}
                
                <label for="id_dns_configured">DNS Configured:</label>{{ form.dns_configured }}

                <label for="id_dns_configured">Wazuh Agent Installed:</label>{{ form.wazuh_agent_installed }}
            </div>
            <div class="column">
                <label for="id_name">Service Name:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.name }}
                
                <label for="id_server">Physical Server:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.server }}
                
                <label for="id_fqdn">FQDN:</label>
                {{ form.fqdn }}
                
                <label for="id_cred_name">Credentials:</label>
                {{ form.credentials }}
                
                <label for="id_network">Network:</label>
                {{ form.network }}
                
                <label for="id_ip">IP Address:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.ip }}
                
                <label for="id_port">Port:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.port }}
                
                <label for="id_ldn">LDN:</label>
                {{ form.ldn }}
            </div>
        </div>
        <button type="submit">Create Service</button>
    </form>
</body>
</html>
{% else %}
{% include 'hmlsvcrapp/_menu.html' %}
<style>
.login-prompt-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
    text-align: center;
}

.login-message {
    font-size: 1.2em;
    margin-bottom: 20px;
    color: #333;
}

.login-button {
    display: inline-block;
    background-color: #009879;
    color: white;
    padding: 10px 20px;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s;
}

.login-button:hover {
    background-color: #007961;
}

</style>
    <div class="login-prompt-container">
        <p><h1>&#128273; <!-- Emoji for red x -->[RESTRICTED]</h1></p>
        <p><h3>You do not have permissions to view this page</h3></p>
    </div>
{% endif %}

hmlsvcrapp/templates/hmlsvcrapp/edit_credential.html
<!-- edit_credential.html -->
{% if request.user.is_authenticated %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Edit Credential</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'hmlsvcrapp/formstyles.css' %}">
</head>
<body>
    <form method="post" class="container">
        {% csrf_token %}
        <h1>Edit Credential</h1>
        <h3>Credential: {{ request.credential.cred_name }}</h3>
        {% if request.user.is_superuser or request.user.is_staff %}
            <div class="form-container">
                <div class="column">
                    <label for="id_mfa_enabled">MFA Enabled:</label>
                    {{ form.mfa_enabled }}

                    <label for="id_mfa_source">MFA Source:</label>
                    {{ form.mfa_source }}

                    <label for="id_sso">SSO:</label>
                    {{ form.sso }}

                    <label for="id_last_updated">Last Updated:</label>
                    {{ form.last_updated }}
                </div>
                <div class="column">
                    <label for="id_username">Username:{% if form.username.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                    {{ form.username }}

                    <label for="id_password">Password:{% if form.password.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                    {{ form.password }}

                    <label for="id_account_type">Account Type:{% if form.account_type.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                    {{ form.account_type }}

                    <label for="id_cred_name">Credential Name:{% if form.cred_name.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                    {{ form.cred_name }}

                    <label for="id_associated_server">Associated Server:</label>
                    {{ form.associated_server }}

                    <label for="id_associated_service">Associated Service:</label>
                    {{ form.associated_service }}
                </div>
            </div>
            <div class="button-container">
                <button type="submit">Save Credential</button>
            </div>
        {% else %}
            <p><h1>&#128273; <!-- Emoji for red x -->[RESTRICTED]</h1></p>
            <p><h3>You do not have permissions to view this page</h3></p>
        {% endif %}
    </form>
</body>
</html>
{% else %}
{% include 'hmlsvcrapp/_menu.html' %}
<style>
.login-prompt-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
    text-align: center;
}

.login-message {
    font-size: 1.2em;
    margin-bottom: 20px;
    color: #333;
}

.login-button {
    display: inline-block;
    background-color: #009879;
    color: white;
    padding: 10px 20px;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s;
}

.login-button:hover {
    background-color: #007961;
}

</style>
    <div class="login-prompt-container">
        <p class="login-message">You must be logged in to view this page.</p>
        <a href="{% url 'login' %}" class="login-button">Log in</a>
    </div>
{% endif %}

hmlsvcrapp/templates/hmlsvcrapp/edit_service.html
{% if request.user.is_authenticated and request.user.is_superuser or request.user.is_staff %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Service</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'hmlsvcrapp/formstyles.css' %}">
</head>
<body>
    <form method="post" class="container">
        <h1>Edit Service</h1>
        <div class="form-container">
            {% csrf_token %}
            <div class="column">
                <label for="id_status">Status:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.status }}
                
                <label for="id_https_enabled">HTTPS:</label>{{ form.https_enabled }}
                
                <label for="id_cloudflare_proxy_configured">Cloudflare:</label>{{ form.cloudflare_proxy_configured }}
                
                <label for="id_reverse_proxy_configured">Reverse Proxy:</label>{{ form.reverse_proxy_configured }}
                
                <label for="id_dns_configured">DNS Configured:</label>{{ form.dns_configured }}

                <label for="id_dns_configured">Wazuh Agent Installed:</label>{{ form.wazuh_agent_installed }}
            </div>
            <div class="column">
                <label for="id_name">Service Name:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.name }}
                
                <label for="id_server">Physical Server:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.server }}
                
                <label for="id_fqdn">FQDN:</label>
                {{ form.fqdn }}
                
                <label for="id_cred_name">Credentials:</label>
                {{ form.credentials }}
                
                <label for="id_network">Network:</label>
                {{ form.network }}
                
                <label for="id_ip">IP Address:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.ip }}
                
                <label for="id_port">Port:{% if form.server.field.required %}<span style="color: red;">*</span>{% endif %}</label>
                {{ form.port }}
                
                <label for="id_ldn">LDN:</label>
                {{ form.ldn }}
            </div>
        </div>
        <div class="button-container">
            <button type="submit">Save Changes</button>
        </div>
    </form>
</body>
</html>
{% else %}
{% include 'hmlsvcrapp/_menu.html' %}
<style>
.login-prompt-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
    text-align: center;
}

.login-message {
    font-size: 1.2em;
    margin-bottom: 20px;
    color: #333;
}

.login-button {
    display: inline-block;
    background-color: #009879;
    color: white;
    padding: 10px 20px;
    text-decoration: none;
    border-radius: 5px;
    transition: background-color 0.3s;
}

.login-button:hover {
    background-color: #007961;
}

</style>
    <div class="login-prompt-container">
        <p><h1>&#128273; <!-- Emoji for red x -->[RESTRICTED]</h1></p>
        <p><h3>You do not have permissions to view this page</h3></p>
    </div>
{% endif %}